const today = new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium'}).format(new Date());
const seed = {
  locations:['A','B','C','D'].flatMap(rack=>Array.from({length:4},(_,levelIndex)=>Array.from({length:6},(_,binIndex)=>{const level=String(levelIndex+1),bin=String(binIndex+1);return {id:`${rack}-${level.padStart(2,'0')}-${bin.padStart(2,'0')}`,name:`${rack}架・${level}層・${bin}格`,rack,level,bin};})).flat()),
  parts:[
    {id:'p1',order:'080410018P',no:'G-UC-312-B006-GI',name:'小球防跳板',book:5},
    {id:'p2',order:'080410018P',no:'UC-122-A001-WE',name:'前控座・白',book:5},
    {id:'p3',order:'080410018P',no:'UC-122-A003-WE',name:'操作面板（LCM・2按）・白',book:5},
    {id:'p4',order:'140909001P',no:'UC-158-F013-WE',name:'前門內貼・白',book:30},
    {id:'p5',order:'140909007P',no:'UC-158-F013-WE',name:'前門內貼・白',book:20}
  ],
  counts:[]
};
let state=JSON.parse(localStorage.getItem('inventory-demo')||'null')||seed;
state.parts=state.parts.map(p=>({...p,isActive:p.isActive!==false,orderPartId:p.orderPartId||p.id}));
state.catalog=state.catalog||state.parts.map(p=>({...p}));
let currentLocation=null,currentPart=null,cloudMode=false,currentUser=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
let pendingImport=null;
function persist(){if(!cloudMode)localStorage.setItem('inventory-demo',JSON.stringify(state));}
function setConnection(mode,label){const button=$('#account-button');button.classList.remove('cloud','local');button.classList.add(mode);$('#sync-text').textContent=label;$('#user-mode').textContent=mode==='cloud'?'共用雲端資料':'本機示範模式';}
async function reloadCloud(){const previousLocation=currentLocation?.id;setConnection('cloud','同步資料中');state=await window.cloud.loadState();currentLocation=state.locations.find(l=>l.id===previousLocation)||null;currentPart=null;$('#current-location').textContent=currentLocation?`${currentLocation.id}｜${currentLocation.name}`:'尚未選擇';$('#part-form').hidden=true;$('#empty-part').hidden=false;renderRecent();renderDashboard();renderSearch();renderManage();setConnection('cloud',currentUser?.email||'共用資料已同步');}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function totalFor(partId,exceptLocation){return state.counts.filter(c=>c.partId===partId&&c.location!==exceptLocation).reduce((s,c)=>s+c.qty,0);}
function statusFor(p){const actual=totalFor(p.id);if(!state.counts.some(c=>c.partId===p.id))return ['未清點','neutral'];if(actual===p.book)return ['數量一致','good'];if(actual<p.book)return ['數量不足','bad'];return ['數量超出','warn'];}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const labels={count:'現場盤點',dashboard:'盤點總覽',search:'資料查詢',manage:'構件管理',import:'Excel 匯入'};$('#page-title').textContent=labels[name];if(name==='dashboard')renderDashboard();if(name==='search')renderSearch();if(name==='manage')renderManage();}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
let locationDraft={step:'rack',rack:null,level:null,bin:null,location:null};
function locationParts(location){const chunks=String(location.id||'').split('-');return {rack:location.rack||chunks[0]||'未分類',level:location.level||chunks[1]||'未分類',bin:location.bin||chunks.slice(2).join('-')||'未分類'};}
function locationValues(key,filters={}){return [...new Set(state.locations.filter(l=>{const p=locationParts(l);return (!filters.rack||p.rack===filters.rack)&&(!filters.level||p.level===filters.level);}).map(l=>locationParts(l)[key]))].sort((a,b)=>a.localeCompare(b,'zh-Hant',{numeric:true}));}
function renderLocationStep(){const d=locationDraft,list=$('#location-list'),back=$('#back-location'),confirm=$('#confirm-location');back.hidden=d.step==='rack';confirm.hidden=d.step!=='confirm';$('#location-breadcrumb').textContent=[d.rack&&`${d.rack}架`,d.level&&`${d.level}層`,d.bin&&`${d.bin}格`].filter(Boolean).join(' → ')||'尚未選擇';const titles={rack:'選擇架位',level:'選擇層位',bin:'選擇格位',confirm:'確認儲位'};$('#location-step-title').textContent=titles[d.step];if(d.step==='confirm'){list.innerHTML=`<div class="variance good">將鎖定：${esc(d.location.name||`${d.rack}架・${d.level}層・${d.bin}格`)}</div>`;return;}const values=locationValues(d.step,d);const suffix={rack:'架',level:'層',bin:'格'}[d.step];list.innerHTML=values.map(v=>`<button class="location-option" type="button" data-value="${esc(v)}"><strong>${esc(v)}${suffix}</strong></button>`).join('')||'<div class="variance warn">這個選項下沒有可用儲位</div>';$$('.location-option').forEach(button=>button.onclick=()=>{const value=button.dataset.value;if(d.step==='rack'){d.rack=value;d.level=null;d.bin=null;d.step='level';}else if(d.step==='level'){d.level=value;d.bin=null;d.step='bin';}else{d.bin=value;d.location=state.locations.find(l=>{const p=locationParts(l);return p.rack===d.rack&&p.level===d.level&&p.bin===d.bin;});d.step='confirm';}renderLocationStep();});}
function openLocations(){locationDraft={step:'rack',rack:null,level:null,bin:null,location:null};$('#location-dialog').hidden=false;renderLocationStep();}
$('#change-location').onclick=openLocations;$('#close-location').onclick=()=>$('#location-dialog').hidden=true;$('#back-location').onclick=()=>{if(locationDraft.step==='confirm')locationDraft.step='bin';else if(locationDraft.step==='bin')locationDraft.step='level';else if(locationDraft.step==='level')locationDraft.step='rack';renderLocationStep();};$('#confirm-location').onclick=()=>{if(!locationDraft.location)return;currentLocation=locationDraft.location;$('#current-location').textContent=`${currentLocation.id}｜${currentLocation.name}`;$('#location-dialog').hidden=true;renderRecent();toast('已鎖定目前儲位');};$('#location-dialog').addEventListener('click',e=>{if(e.target.id==='location-dialog')e.currentTarget.hidden=true;});
function searchParts(q){q=q.trim().toLowerCase();return q?state.parts.filter(p=>p.isActive!==false&&[p.no,p.order,p.name].some(v=>v.toLowerCase().includes(q))).slice(0,8):[];}
function renderPartResults(q){const found=searchParts(q);$('#search-results').innerHTML=found.map(p=>`<button class="result-item" data-id="${esc(p.id)}"><span><strong>${esc(p.no)}</strong><small>${esc(p.name)}・訂單 ${esc(p.order)}</small></span><span class="result-qty">帳面 ${p.book}</span></button>`).join('')||(q?'<div class="variance warn">查無構件，可到資料查詢確認編號。</div>':'');$$('.result-item').forEach(b=>b.onclick=()=>selectPart(b.dataset.id));}
$('#part-search').addEventListener('input',e=>renderPartResults(e.target.value));
function selectPart(id){if(!currentLocation){openLocations();toast('請先選擇儲位');return;}currentPart=state.parts.find(p=>p.id===id);$('#empty-part').hidden=true;$('#part-form').hidden=false;$('#part-name').textContent=currentPart.name;$('#part-no').textContent=currentPart.no;$('#order-no').textContent=currentPart.order;$('#book-qty').textContent=currentPart.book;$('#other-qty').textContent=totalFor(currentPart.id,currentLocation.id);const s=statusFor(currentPart);$('#part-status').textContent=s[0];$('#part-status').className=`status ${s[1]}`;const existing=state.counts.find(c=>c.partId===id&&c.location===currentLocation.id);$('#actual-qty').value=existing?.qty??'';$('#verified').checked=Boolean(existing?.verified);$('#note').value=existing?.note??'';$('#verify-date').textContent=`確認日：${today}`;$('#search-results').innerHTML='';$('#part-search').value='';updateVariance();$('#actual-qty').focus();}
function updateVariance(){if(!currentPart)return;const raw=$('#actual-qty').value;if(raw===''){ $('#variance-banner').textContent='輸入數量後顯示差異';$('#variance-banner').className='variance neutral';return;}const qty=Number(raw),total=totalFor(currentPart.id,currentLocation.id)+qty,diff=total-currentPart.book;const text=diff===0?'數量一致':diff<0?`數量不足 ${Math.abs(diff)}`:`數量超出 ${diff}`;$('#variance-banner').textContent=`盤點總數 ${total}｜${text}`;$('#variance-banner').className=`variance ${diff===0?'good':diff<0?'bad':'warn'}`;}
$('#actual-qty').addEventListener('input',updateVariance);$('#qty-minus').onclick=()=>{const i=$('#actual-qty');i.value=Math.max(0,Number(i.value||0)-1);updateVariance();};$('#qty-plus').onclick=()=>{const i=$('#actual-qty');i.value=Number(i.value||0)+1;updateVariance();};$('#use-remaining').onclick=()=>{if(!currentPart)return;$('#actual-qty').value=Math.max(0,currentPart.book-totalFor(currentPart.id,currentLocation.id));updateVariance();};
$('#save-count').onclick=async()=>{if(!currentLocation||!currentPart)return;const raw=$('#actual-qty').value;if(raw===''||!Number.isInteger(Number(raw))||Number(raw)<0){toast('請輸入有效的整數數量');return;}const qty=Number(raw),verified=$('#verified').checked,note=$('#note').value.trim(),part=currentPart,location=currentLocation;try{if(cloudMode){setConnection('cloud','正在儲存');await window.cloud.saveCount({part,location,qty,verified,note});await reloadCloud();toast('已同步到共用資料');}else{let record=state.counts.find(c=>c.partId===part.id&&c.location===location.id);if(record){record.qty=qty;record.verified=verified;record.note=note;record.at=new Date().toISOString();toast('已更新本儲位紀錄');}else{state.counts.unshift({id:crypto.randomUUID(),partId:part.id,location:location.id,qty,verified,note,at:new Date().toISOString()});toast('盤點已儲存');}persist();currentPart=null;$('#part-form').hidden=true;$('#empty-part').hidden=false;renderRecent();}$('#part-search').focus();}catch(error){setConnection('cloud','同步失敗');toast(`儲存失敗：${error.message}`);}};
function renderRecent(){const rows=state.counts.filter(c=>!currentLocation||c.location===currentLocation.id).slice(0,8);$('#recent-list').innerHTML=rows.map(c=>{const p=state.parts.find(p=>p.id===c.partId);return `<div class="recent-row"><div><strong>${esc(p?.no||'未知構件')}</strong><small>${esc(p?.name||'')}・${esc(c.location)}</small></div><span class="qty">${c.qty} 件</span><small class="when">${new Date(c.at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}</small></div>`}).join('')||'<div class="empty-state"><p>此儲位尚無盤點紀錄</p></div>';}
$('#complete-location').onclick=()=>currentLocation?toast(`${currentLocation.id} 已標記完成`):toast('請先選擇儲位');
function renderDashboard(){const totals=state.parts.filter(p=>p.isActive!==false).map(p=>({...p,actual:totalFor(p.id)}));const completed=totals.filter(p=>p.actual>0).length,match=totals.filter(p=>p.actual===p.book&&p.actual>0).length,short=totals.filter(p=>p.actual<p.book&&p.actual>0).length,over=totals.filter(p=>p.actual>p.book).length;const cards=[['盤點目標',totals.length],['已盤構件',completed],['數量一致',match],['數量異常',short+over]];$('#kpi-grid').innerHTML=cards.map(c=>`<button class="kpi"><span>${esc(c[0])}</span><strong>${c[1]}</strong></button>`).join('');$('#dashboard-table').innerHTML=totals.map(p=>{const d=p.actual-p.book,s=statusFor(p);return `<tr><td>${esc(p.order)}</td><td><strong>${esc(p.no)}</strong></td><td>${p.book}</td><td>${p.actual}</td><td>${d>0?'+':''}${d}</td><td><span class="status ${s[1]}">${s[0]}</span></td></tr>`}).join('');}
function renderSearch(q=''){q=q.toLowerCase();const rows=state.parts.filter(p=>p.isActive!==false&&(!q||[p.order,p.no,p.name,...state.counts.filter(c=>c.partId===p.id).map(c=>c.location)].some(v=>v.toLowerCase().includes(q))));$('#search-table').innerHTML=rows.map(p=>{const locs=[...new Set(state.counts.filter(c=>c.partId===p.id).map(c=>c.location))];return `<tr><td>${esc(p.order)}</td><td><strong>${esc(p.no)}</strong></td><td>${esc(p.name)}</td><td>${p.book}</td><td>${totalFor(p.id)}</td><td>${esc(locs.join('、')||'—')}</td></tr>`}).join('');}
$('#global-search').addEventListener('input',e=>renderSearch(e.target.value));
let batchLookupRows=[];
function exactKey(value){return String(value??'').trim().toUpperCase();}
function parseLookupWorkbook(workbook){const results=[];let inputCount=0;for(const sheetName of workbook.SheetNames){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:null,raw:false});const headerIndex=rows.findIndex((row,index)=>index<20&&row.some(cell=>['物品編號','構件編號','零件編號'].includes(normalizeHeader(cell))));if(headerIndex<0){results.push({sheet:sheetName,row:'—',inputOrder:'',inputPart:'',matchedOrder:'',name:'',locations:'',result:'找不到構件編號欄',kind:'bad'});continue;}const headers=rows[headerIndex].map(normalizeHeader),partIndex=headers.findIndex(h=>['物品編號','構件編號','零件編號'].includes(h)),orderIndex=headers.findIndex(h=>['採購單編號','訂單編號'].includes(h));for(let index=headerIndex+1;index<rows.length;index++){const inputPart=String(rows[index][partIndex]??'').trim();if(!inputPart)continue;inputCount++;const inputOrder=orderIndex>=0?String(rows[index][orderIndex]??'').trim():'';const matches=state.parts.filter(p=>p.isActive!==false&&exactKey(p.no)===exactKey(inputPart)&&(!inputOrder||exactKey(p.order)===exactKey(inputOrder)));if(!matches.length){results.push({sheet:sheetName,row:index+1,inputOrder,inputPart,matchedOrder:'—',name:'—',locations:'—',result:'查無符合構件',kind:'bad'});continue;}const multiple=!inputOrder&&matches.length>1;for(const part of matches){const entries=state.counts.filter(c=>c.partId===part.id),locations=entries.map(c=>`${c.location}：${c.qty}件`).join('；');results.push({sheet:sheetName,row:index+1,inputOrder,inputPart,matchedOrder:part.order,name:part.name,locations:locations||'尚未登記儲位',result:locations?(multiple?'同構件有多個訂單':'已找到'):'尚未盤點',kind:locations?(multiple?'warn':'good'):'warn'});}}}return {results,inputCount};}
function renderLookup(){const tbody=$('#lookup-table');tbody.innerHTML=batchLookupRows.map(row=>`<tr><td>${esc(row.sheet)}／${esc(row.row)}</td><td>${esc(row.inputOrder||'—')}</td><td><strong>${esc(row.inputPart||'—')}</strong></td><td>${esc(row.matchedOrder)}</td><td>${esc(row.name)}</td><td>${esc(row.locations)}</td><td><span class="lookup-result ${row.kind}">${esc(row.result)}</span></td></tr>`).join('')||'<tr><td colspan="7">尚未上傳查詢清單</td></tr>';}
$('#lookup-file').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!window.XLSX){toast('Excel 讀取元件尚未載入');return;}const reader=new FileReader();reader.onload=e=>{try{const parsed=parseLookupWorkbook(XLSX.read(e.target.result,{type:'array'}));batchLookupRows=parsed.results;const found=batchLookupRows.filter(r=>r.kind!=='bad').length,missing=batchLookupRows.filter(r=>r.kind==='bad').length;$('#lookup-summary').innerHTML=`<div class="variance ${missing?'warn':'good'}">輸入 ${parsed.inputCount} 項｜找到 ${found} 筆對應結果｜查無 ${missing} 筆</div>`;$('#export-lookup').hidden=batchLookupRows.length===0;renderLookup();}catch(error){batchLookupRows=[];$('#export-lookup').hidden=true;$('#lookup-summary').innerHTML='<div class="variance bad">無法讀取此 Excel，請確認檔案格式。</div>';renderLookup();}};reader.readAsArrayBuffer(file);});
$('#export-lookup').onclick=()=>{if(!batchLookupRows.length||!window.XLSX)return;const rows=batchLookupRows.map(row=>({'來源工作表':row.sheet,'來源列':row.row,'輸入訂單':row.inputOrder,'構件編號':row.inputPart,'比對訂單':row.matchedOrder,'零件名稱':row.name,'實際儲位與數量':row.locations,'查詢結果':row.result}));const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(rows),'儲位查詢結果');XLSX.writeFile(workbook,`批量儲位查詢_${new Date().toISOString().slice(0,10)}.xlsx`);};
function managementRows(){return state.catalog||state.parts;}
function targetForManagementRow(row){return state.parts.find(part=>part.orderPartId===row.orderPartId);}
function entriesForManagementRow(row){const target=targetForManagementRow(row);return target?state.counts.filter(entry=>entry.partId===target.id):[];}
function dateInputValue(value){if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10);}
function isoFromDate(value){return value?new Date(`${value}T12:00:00`).toISOString():null;}
function setCascade(prefix,locationId=''){
  const rackEl=$(`#${prefix}-rack`),levelEl=$(`#${prefix}-level`),binEl=$(`#${prefix}-bin`);if(!rackEl||!levelEl||!binEl)return;
  const selected=state.locations.find(location=>location.id===locationId),parts=selected?locationParts(selected):{};
  const fill=(element,values,selectedValue,placeholder,suffix)=>{element.innerHTML=`<option value="">${placeholder}</option>${values.map(value=>`<option value="${esc(value)}">${esc(value)}${suffix}</option>`).join('')}`;element.value=selectedValue||'';};
  const refreshBins=selectedValue=>fill(binEl,levelEl.value?locationValues('bin',{rack:rackEl.value,level:levelEl.value}):[],selectedValue,'選格','格');
  const refreshLevels=(selectedLevel,selectedBin)=>{fill(levelEl,rackEl.value?locationValues('level',{rack:rackEl.value}):[],selectedLevel,'選層','層');refreshBins(selectedBin);};
  fill(rackEl,locationValues('rack'),parts.rack,'選架','架');refreshLevels(parts.level,parts.bin);
  rackEl.onchange=()=>refreshLevels('','');levelEl.onchange=()=>refreshBins('');
}
function cascadeLocation(prefix){const rack=$(`#${prefix}-rack`).value,level=$(`#${prefix}-level`).value,bin=$(`#${prefix}-bin`).value;return state.locations.find(location=>{const parts=locationParts(location);return parts.rack===rack&&parts.level===level&&parts.bin===bin;});}
function populateManageLocationFilter(){const select=$('#manage-location-filter'),current=select.value;select.innerHTML='<option value="">所有儲位</option>'+state.locations.map(location=>`<option value="${esc(location.id)}">${esc(location.id)}｜${esc(location.name)}</option>`).join('');select.value=state.locations.some(location=>location.id===current)?current:'';}
let selectedManageIds=new Set(),visibleManageRows=[];
function updateBatchSelectionBar(){const count=selectedManageIds.size;$('#selected-manage-count').textContent=count;$('#batch-selection-bar').hidden=count===0;}
function renderManage(){
  populateManageLocationFilter();
  const q=$('#manage-search').value.trim().toLowerCase(),filter=$('#manage-filter').value,locationFilter=$('#manage-location-filter').value;
  const rows=managementRows().filter(row=>{const entries=entriesForManagementRow(row);return (filter==='all'||(filter==='active')===(row.isActive!==false))&&(!q||[row.order,row.no,row.name].some(value=>String(value||'').toLowerCase().includes(q)))&&(!locationFilter||entries.some(entry=>entry.location===locationFilter));});
  visibleManageRows=rows;
  const validIds=new Set(managementRows().map(row=>row.orderPartId));selectedManageIds=new Set([...selectedManageIds].filter(id=>validIds.has(id)));
  $('#manage-table').innerHTML=rows.map(row=>{const target=targetForManagementRow(row),entries=entriesForManagementRow(row),actual=target?totalFor(target.id):0,locations=[...new Set(entries.map(entry=>entry.location))],verifiedEntries=entries.filter(entry=>entry.verified),baseline=!entries.length?'—':!verifiedEntries.length?'未確認':verifiedEntries.length===entries.length?(dateInputValue(verifiedEntries[0].verifiedAt)||'已確認'):`${verifiedEntries.length}/${entries.length} 已確認`,batchable=entries.length===1;return `<tr><td><input class="manage-row-check" type="checkbox" data-select-count="${esc(row.orderPartId)}" ${selectedManageIds.has(row.orderPartId)?'checked':''} ${batchable?'':`disabled title="${entries.length?'多個儲位請逐筆修改':'尚未盤點'}"`}></td><td>${esc(row.order)}</td><td><strong>${esc(row.no)}</strong><span class="table-sub">${esc(row.name)}</span></td><td>${row.book}</td><td>${actual}</td><td>${esc(locations.join('、')||'—')}</td><td><span class="status ${verifiedEntries.length?'good':'neutral'}">${esc(baseline)}</span></td><td><span class="status ${row.isActive!==false?'good':'neutral'}">${row.isActive!==false?'使用中':'已停用'}</span></td><td><div class="table-action-group"><button type="button" class="table-action" data-count-edit="${esc(row.orderPartId)}" ${entries.length?'':'disabled'}>盤點修正</button><button type="button" class="table-action" data-edit="${esc(row.orderPartId)}">帳面編輯</button>${row.isActive!==false?`<button type="button" class="table-action danger" data-disable="${esc(row.orderPartId)}">停用</button>`:`<button type="button" class="table-action restore" data-restore="${esc(row.orderPartId)}">恢復</button>`}</div></td></tr>`;}).join('')||'<tr><td colspan="9">沒有符合的構件</td></tr>';
  const batchableRows=rows.filter(row=>entriesForManagementRow(row).length===1),selectAll=$('#select-manage-visible');selectAll.checked=batchableRows.length>0&&batchableRows.every(row=>selectedManageIds.has(row.orderPartId));selectAll.indeterminate=batchableRows.some(row=>selectedManageIds.has(row.orderPartId))&&!selectAll.checked;
  $$('.manage-row-check').forEach(input=>input.onchange=()=>{input.checked?selectedManageIds.add(input.dataset.selectCount):selectedManageIds.delete(input.dataset.selectCount);updateBatchSelectionBar();renderManage();});
  $$('[data-count-edit]').forEach(button=>button.onclick=()=>openCountEditor(button.dataset.countEdit));$$('[data-edit]').forEach(button=>button.onclick=()=>openEditPart(button.dataset.edit));$$('[data-disable]').forEach(button=>button.onclick=()=>openDisable(button.dataset.disable));$$('[data-restore]').forEach(button=>button.onclick=()=>restoreManagedPart(button.dataset.restore));updateBatchSelectionBar();
}
$('#manage-search').addEventListener('input',renderManage);$('#manage-filter').addEventListener('change',renderManage);$('#manage-location-filter').addEventListener('change',renderManage);
$('#select-manage-visible').addEventListener('change',event=>{visibleManageRows.filter(row=>entriesForManagementRow(row).length===1).forEach(row=>event.target.checked?selectedManageIds.add(row.orderPartId):selectedManageIds.delete(row.orderPartId));renderManage();});
$('#clear-manage-selection').onclick=()=>{selectedManageIds.clear();renderManage();};
let editingOrderPartId=null;
function syncVerifiedDate(checkId,dateId){const checked=$(checkId).checked,date=$(dateId);date.disabled=!checked;if(checked&&!date.value)date.value=new Date().toISOString().slice(0,10);if(!checked)date.value='';}
$('#manual-create-count').onchange=()=>{$('#new-count-fields').hidden=!$('#manual-create-count').checked;};$('#manual-verified').onchange=()=>syncVerifiedDate('#manual-verified','#manual-verified-date');
$('#add-part').onclick=()=>{editingOrderPartId=null;$('#part-form-manage').reset();$('#manual-create-count').checked=true;$('#new-count-section').hidden=false;$('#new-count-fields').hidden=false;$('#manual-order').disabled=false;$('#manual-part-no').disabled=false;$('#manage-dialog-title').textContent='新增構件並盤點';$('#manage-part-submit').textContent='新增並完成盤點';$('#part-manage-error').hidden=true;setCascade('manual');syncVerifiedDate('#manual-verified','#manual-verified-date');$('#part-dialog').hidden=false;$('#manual-order').focus();};$('#close-part-dialog').onclick=()=>$('#part-dialog').hidden=true;
function openEditPart(id){const row=managementRows().find(part=>part.orderPartId===id);if(!row)return;editingOrderPartId=id;$('#part-form-manage').reset();$('#new-count-section').hidden=true;$('#manual-order').value=row.order;$('#manual-part-no').value=row.no;$('#manual-part-name').value=row.name;$('#manual-drawing').value=row.drawingNo||'';$('#manual-book').value=row.book;$('#manual-order').disabled=true;$('#manual-part-no').disabled=true;$('#manage-dialog-title').textContent='編輯訂單構件';$('#manage-part-submit').textContent='儲存帳面修改';$('#part-manage-error').hidden=true;$('#part-dialog').hidden=false;$('#manual-part-name').focus();}
$('#part-form-manage').addEventListener('submit',async event=>{event.preventDefault();const errorBox=$('#part-manage-error'),item={order:$('#manual-order').value.trim(),no:$('#manual-part-no').value.trim(),name:$('#manual-part-name').value.trim(),drawingNo:$('#manual-drawing').value.trim(),book:Number($('#manual-book').value),reason:$('#manual-reason').value.trim()},createCount=!editingOrderPartId&&$('#manual-create-count').checked,actualRaw=$('#manual-actual').value,qty=Number(actualRaw),location=createCount?cascadeLocation('manual'):null,verified=createCount&&$('#manual-verified').checked,verifiedAt=verified?isoFromDate($('#manual-verified-date').value):null;errorBox.hidden=true;if(!Number.isInteger(item.book)||item.book<0){errorBox.textContent='帳面數量必須是零或正整數';errorBox.hidden=false;return;}if(createCount&&(actualRaw===''||!Number.isInteger(qty)||qty<0||!location)){errorBox.textContent='同時盤點時，請輸入有效數量並完整選擇架、層、格';errorBox.hidden=false;return;}if(verified&&!verifiedAt){errorBox.textContent='請輸入圖面確認日期';errorBox.hidden=false;return;}const duplicate=!editingOrderPartId&&managementRows().find(part=>part.order===item.order&&part.no===item.no);if(duplicate){errorBox.textContent=duplicate.isActive!==false?'相同採購單與構件編號已存在':'這筆構件已停用，請從列表按「恢復」';errorBox.hidden=false;return;}try{if(cloudMode){setConnection('cloud',editingOrderPartId?'正在修改':'正在新增');if(editingOrderPartId)await window.cloud.updateOrderPart(editingOrderPartId,item);else{const saved=await window.cloud.addOrderPart(item);if(createCount)await window.cloud.saveCount({part:{targetId:saved.targetId},location,qty,verified,note:$('#manual-count-note').value.trim(),verifiedAt});}await reloadCloud();}else if(editingOrderPartId){state.parts.filter(part=>part.orderPartId===editingOrderPartId).forEach(part=>Object.assign(part,{name:item.name,drawingNo:item.drawingNo,book:item.book}));state.catalog.filter(part=>part.orderPartId===editingOrderPartId).forEach(part=>Object.assign(part,{name:item.name,drawingNo:item.drawingNo,book:item.book}));persist();renderManage();}else{const id=crypto.randomUUID(),part={id,orderPartId:id,...item,isActive:true};state.parts.push(part);state.catalog.push({...part});if(createCount)state.counts.unshift({id:crypto.randomUUID(),partId:id,location:location.id,locationDbId:location.dbId,qty,verified,verifiedAt,note:$('#manual-count-note').value.trim(),at:new Date().toISOString(),updatedAt:new Date().toISOString()});persist();renderManage();}$('#part-dialog').hidden=true;toast(editingOrderPartId?'構件帳面資料已修改':createCount?'構件已新增並完成盤點':'構件已新增');editingOrderPartId=null;}catch(error){errorBox.textContent=`儲存失敗：${error.message}`;errorBox.hidden=false;setConnection(cloudMode?'cloud':'local','儲存失敗');}});
let countEditingRow=null;
function loadCountEntryEditor(){if(!countEditingRow)return;const entry=state.counts.find(item=>item.id===$('#count-entry-select').value);if(!entry)return;$('#count-edit-qty').value=entry.qty;setCascade('count-edit',entry.location);$('#count-edit-verified').checked=Boolean(entry.verified);$('#count-edit-verified-date').value=dateInputValue(entry.verifiedAt);$('#count-edit-note').value=entry.note||'';syncVerifiedDate('#count-edit-verified','#count-edit-verified-date');}
function openCountEditor(orderPartId){const row=managementRows().find(item=>item.orderPartId===orderPartId),entries=row?entriesForManagementRow(row):[];if(!row||!entries.length){toast('此構件尚無盤點紀錄');return;}countEditingRow=row;$('#count-edit-part-label').textContent=`${row.order}｜${row.no}｜${row.name}`;$('#count-entry-select').innerHTML=entries.map(entry=>`<option value="${esc(entry.id)}">${esc(entry.location)}｜${entry.qty} 件</option>`).join('');$('#count-edit-reason').value='';$('#count-edit-error').hidden=true;loadCountEntryEditor();$('#count-edit-dialog').hidden=false;}
$('#count-entry-select').onchange=loadCountEntryEditor;$('#count-edit-verified').onchange=()=>syncVerifiedDate('#count-edit-verified','#count-edit-verified-date');$('#close-count-edit').onclick=()=>$('#count-edit-dialog').hidden=true;
$('#count-edit-form').addEventListener('submit',async event=>{event.preventDefault();const entry=state.counts.find(item=>item.id===$('#count-entry-select').value),location=cascadeLocation('count-edit'),qty=Number($('#count-edit-qty').value),verified=$('#count-edit-verified').checked,verifiedAt=verified?isoFromDate($('#count-edit-verified-date').value):null,note=$('#count-edit-note').value.trim(),reason=$('#count-edit-reason').value.trim(),errorBox=$('#count-edit-error');errorBox.hidden=true;if(!entry||!location||!Number.isInteger(qty)||qty<0){errorBox.textContent='請輸入有效數量並完整選擇架、層、格';errorBox.hidden=false;return;}if(verified&&!verifiedAt){errorBox.textContent='請輸入圖面確認日期';errorBox.hidden=false;return;}try{if(cloudMode){setConnection('cloud','正在修正盤點資料');await window.cloud.updateCountEntry(entry.id,{locationDbId:location.dbId,qty,verified,verifiedAt,note,reason});await reloadCloud();}else{Object.assign(entry,{location:location.id,locationDbId:location.dbId,qty,verified,verifiedAt,note,updatedAt:new Date().toISOString()});persist();renderManage();}$('#count-edit-dialog').hidden=true;toast('盤點資料已修改並保留歷程');}catch(error){errorBox.textContent=`修改失敗：${error.message}`;errorBox.hidden=false;setConnection(cloudMode?'cloud':'local','修改失敗');}});
$('#batch-location-action').onchange=()=>{$('#batch-location-fields').hidden=$('#batch-location-action').value!=='change';if($('#batch-location-action').value==='change')setCascade('batch');};$('#batch-verification-action').onchange=()=>{$('#batch-verified-date-wrap').hidden=$('#batch-verification-action').value!=='confirm';if($('#batch-verification-action').value==='confirm'&&!$('#batch-verified-date').value)$('#batch-verified-date').value=new Date().toISOString().slice(0,10);};
$('#open-batch-edit').onclick=()=>{const rows=managementRows().filter(row=>selectedManageIds.has(row.orderPartId)&&entriesForManagementRow(row).length===1);if(!rows.length){toast('請先選取可批次修改的構件');return;}$('#batch-edit-form').reset();$('#batch-edit-count').textContent=rows.length;$('#batch-location-fields').hidden=true;$('#batch-verified-date-wrap').hidden=true;$('#batch-edit-error').hidden=true;setCascade('batch');$('#batch-edit-dialog').hidden=false;};$('#close-batch-edit').onclick=()=>$('#batch-edit-dialog').hidden=true;
$('#batch-edit-form').addEventListener('submit',async event=>{event.preventDefault();const rows=managementRows().filter(row=>selectedManageIds.has(row.orderPartId)&&entriesForManagementRow(row).length===1),entries=rows.map(row=>entriesForManagementRow(row)[0]),locationAction=$('#batch-location-action').value,location=locationAction==='change'?cascadeLocation('batch'):null,verificationAction=$('#batch-verification-action').value,verifiedAt=verificationAction==='confirm'?isoFromDate($('#batch-verified-date').value):null,reason=$('#batch-edit-reason').value.trim(),errorBox=$('#batch-edit-error'),submit=$('#batch-edit-submit');errorBox.hidden=true;if(locationAction==='keep'&&verificationAction==='keep'){errorBox.textContent='請至少選擇一項要修改的內容';errorBox.hidden=false;return;}if(locationAction==='change'&&!location){errorBox.textContent='請完整選擇新的架、層、格';errorBox.hidden=false;return;}if(verificationAction==='confirm'&&!verifiedAt){errorBox.textContent='請輸入圖面確認日期';errorBox.hidden=false;return;}if(location&&entries.some(entry=>state.counts.some(other=>other.partId===entry.partId&&other.id!==entry.id&&other.location===location.id))){errorBox.textContent='選取項目中有構件在目標儲位已有紀錄，請改用逐筆修正';errorBox.hidden=false;return;}submit.disabled=true;try{if(cloudMode){setConnection('cloud','正在批次修正');await window.cloud.batchUpdateCountEntries(entries.map(entry=>entry.id),{locationDbId:location?.dbId||null,verificationAction,verifiedAt,reason},(done,total)=>{submit.textContent=`處理中 ${done}/${total}`;});selectedManageIds.clear();await reloadCloud();}else{entries.forEach(entry=>{if(location)Object.assign(entry,{location:location.id,locationDbId:location.dbId});if(verificationAction==='confirm')Object.assign(entry,{verified:true,verifiedAt});else if(verificationAction==='clear')Object.assign(entry,{verified:false,verifiedAt:null});entry.updatedAt=new Date().toISOString();});persist();selectedManageIds.clear();renderManage();}$('#batch-edit-dialog').hidden=true;toast(`已完成 ${entries.length} 筆批次修正`);}catch(error){errorBox.textContent=`批次修改失敗：${error.message}`;errorBox.hidden=false;setConnection(cloudMode?'cloud':'local','批次修改失敗');}finally{submit.disabled=false;submit.textContent='確認批次修改';}});
let pendingDisableId=null;function openDisable(id){pendingDisableId=id;const row=managementRows().find(p=>p.orderPartId===id);$('#disable-part-label').textContent=row?`${row.order}｜${row.no}｜${row.name}`:'';$('#disable-reason').value='';$('#disable-dialog').hidden=false;$('#disable-reason').focus();}function closeDisable(){pendingDisableId=null;$('#disable-dialog').hidden=true;}$('#close-disable-dialog').onclick=closeDisable;$('#cancel-disable').onclick=closeDisable;
$('#disable-form').addEventListener('submit',async event=>{event.preventDefault();if(!pendingDisableId)return;const reason=$('#disable-reason').value.trim();try{if(cloudMode){setConnection('cloud','正在停用');await window.cloud.setOrderPartActive(pendingDisableId,false,reason);await reloadCloud();}else{state.parts.filter(p=>p.orderPartId===pendingDisableId).forEach(p=>p.isActive=false);state.catalog.filter(p=>p.orderPartId===pendingDisableId).forEach(p=>p.isActive=false);persist();renderManage();}closeDisable();toast('構件已停用，歷史紀錄仍保留');}catch(error){toast(`停用失敗：${error.message}`);}});
async function restoreManagedPart(id){try{if(cloudMode){setConnection('cloud','正在恢復');await window.cloud.setOrderPartActive(id,true,'管理者恢復');await reloadCloud();}else{state.parts.filter(p=>p.orderPartId===id).forEach(p=>p.isActive=true);state.catalog.filter(p=>p.orderPartId===id).forEach(p=>p.isActive=true);persist();renderManage();}toast('構件已恢復使用');}catch(error){toast(`恢復失敗：${error.message}`);}}
$('#camera-button').onclick=()=>toast('相機掃描將在正式連線設定後啟用');
function normalizeHeader(v){return String(v??'').replace(/\s+/g,'').trim();}
function parseWorkbook(wb){const aggregated=new Map();const warnings=[];let sourceRows=0,excluded=0;for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:null,raw:true});const headerIndex=rows.findIndex((r,i)=>i<10&&r.some(v=>normalizeHeader(v)==='物品編號'));if(headerIndex<0){warnings.push(`${sheetName}：找不到「物品編號」標題`);continue;}const headers=rows[headerIndex].map(normalizeHeader);const idx={order:headers.indexOf('採購單編號'),part:headers.indexOf('物品編號'),name:headers.indexOf('品名'),ordered:headers.indexOf('採購數量'),book:headers.indexOf('未交量')};if(idx.order<0||idx.part<0||idx.name<0||idx.book<0){warnings.push(`${sheetName}：必要欄位不完整`);continue;}let order='';for(let r=headerIndex+1;r<rows.length;r++){sourceRows++;const row=rows[r];if(row[idx.order]!=null&&String(row[idx.order]).trim())order=String(row[idx.order]).trim();const part=String(row[idx.part]??'').trim(),name=String(row[idx.name]??'').trim();if(!part||order==='合計'||part.startsWith('備註')){excluded++;continue;}const book=Number(row[idx.book]);if(!order||!Number.isFinite(book)){warnings.push(`${sheetName} 第 ${r+1} 列：訂單或未交量無效`);continue;}const key=`${order}|||${part}`,ordered=idx.ordered>=0&&Number.isFinite(Number(row[idx.ordered]))?Number(row[idx.ordered]):null;if(!aggregated.has(key))aggregated.set(key,{order,no:part,name:name||part,book:0,orderedValues:[],sources:0});const item=aggregated.get(key);item.book+=book;item.sources++;if(ordered!=null)item.orderedValues.push(ordered);if(item.name!==name&&name)warnings.push(`${sheetName} 第 ${r+1} 列：${part} 品名不一致`);}}
  return {items:[...aggregated.values()],warnings,sourceRows,excluded,sheets:wb.SheetNames.length};}
$('#excel-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!window.XLSX){toast('Excel 讀取元件尚未載入');return;}const reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array'});pendingImport=parseWorkbook(wb);const p=pendingImport;$('#import-preview').innerHTML=`<div class="facts" style="margin-top:18px"><div><span>工作表</span><strong>${p.sheets}</strong></div><div><span>可匯入構件</span><strong>${p.items.length}</strong></div><div><span>排除列</span><strong>${p.excluded}</strong></div></div><div class="variance ${p.warnings.length?'warn':'good'}">${p.warnings.length?`有 ${p.warnings.length} 項需要注意；未解析的工作表不會匯入。`:'欄位檢查完成，可以確認匯入。'}</div>`;$('#commit-import').hidden=p.items.length===0;}catch(error){pendingImport=null;$('#commit-import').hidden=true;$('#import-preview').innerHTML='<div class="variance bad" style="margin-top:18px">無法讀取此 Excel，請確認檔案格式。</div>';}};reader.readAsArrayBuffer(file);});
$('#commit-import').onclick=async()=>{if(!pendingImport)return;const button=$('#commit-import'),originalLabel=button.textContent;button.disabled=true;try{if(cloudMode){setConnection('cloud','正在匯入');const count=await window.cloud.importItems(pendingImport.items,({stage,done,total})=>{const detail=total?`${done}/${total}`:'';button.textContent=`${stage} ${detail}`.trim();setConnection('cloud',`${stage} ${detail}`.trim());});button.textContent='正在重新載入';await reloadCloud();toast(`已匯入 ${count} 筆共用帳面資料`);}else{const merged=new Map(state.parts.map(p=>[`${p.order}|||${p.no}`,p]));for(const item of pendingImport.items){const key=`${item.order}|||${item.no}`;if(merged.has(key)){const p=merged.get(key);p.name=item.name;p.book=item.book;}else{const p={id:crypto.randomUUID(),order:item.order,no:item.no,name:item.name,book:item.book};state.parts.push(p);merged.set(key,p);}}persist();toast(`已匯入 ${pendingImport.items.length} 筆本機帳面資料`);}pendingImport=null;button.hidden=true;$('#excel-file').value='';}catch(error){setConnection(cloudMode?'cloud':'local','匯入未完成');$('#import-preview').insertAdjacentHTML('beforeend',`<div class="variance bad">匯入未完成：${esc(error.message)}。相同資料可直接重新匯入，不會重複新增。</div>`);toast(`匯入未完成：${error.message}`);}finally{button.disabled=false;button.textContent=originalLabel;}};
$('#export-results').onclick=()=>{if(!window.XLSX){toast('匯出元件尚未載入');return;}const rows=state.parts.map(p=>{const actual=totalFor(p.id),locations=state.counts.filter(c=>c.partId===p.id).map(c=>`${c.location}:${c.qty}`).join('；');return {'訂單編號':p.order,'物品編號':p.no,'品名':p.name,'帳面數量':p.book,'實際數量':actual,'差異':actual-p.book,'儲位分布':locations,'狀態':statusFor(p)[0]};});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'盤點結果');XLSX.writeFile(wb,`盤點結果_${new Date().toISOString().slice(0,10)}.xlsx`);};
function registerWebMcp(){const context=document.modelContext;if(!context?.registerTool)return;context.registerTool({name:'search_inventory_parts',title:'搜尋構件',description:'依訂單、物品編號或品名搜尋目前盤點資料。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:({query})=>searchParts(String(query)).map(p=>({id:p.id,orderNo:p.order,partNo:p.no,name:p.name,bookQty:p.book,actualQty:totalFor(p.id)}))});}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
registerWebMcp();
$('#auth-form').addEventListener('submit',async event=>{event.preventDefault();const errorBox=$('#auth-error');let signedIn=false;errorBox.hidden=true;try{const email=$('#auth-email').value.trim(),password=$('#auth-password').value;currentUser=await window.cloud.signIn(email,password);signedIn=true;cloudMode=true;await reloadCloud();$('#auth-dialog').hidden=true;toast('登入成功，已載入共用資料');}catch(error){errorBox.textContent=error.message==='Invalid login credentials'?'Email 或密碼不正確':signedIn?`登入成功，但資料載入失敗：${error.message}`:`無法登入：${error.message}`;errorBox.hidden=false;}});
$('#demo-mode').onclick=()=>{cloudMode=false;$('#auth-dialog').hidden=true;setConnection('local','本機示範資料');renderRecent();};
$('#account-button').onclick=async()=>{if(cloudMode){await window.cloud.signOut();cloudMode=false;currentUser=null;state=JSON.parse(localStorage.getItem('inventory-demo')||'null')||seed;state.parts=state.parts.map(p=>({...p,isActive:p.isActive!==false,orderPartId:p.orderPartId||p.id}));state.catalog=state.catalog||state.parts.map(p=>({...p}));setConnection('local','已登出共用資料');renderRecent();renderDashboard();renderSearch();renderManage();$('#auth-dialog').hidden=false;}else $('#auth-dialog').hidden=false;};
async function bootstrap(){renderRecent();if(!window.cloud?.configured){setConnection('local','本機示範資料');return;}try{const authSession=await window.cloud.session();if(authSession){currentUser=authSession.user;cloudMode=true;await reloadCloud();}else{$('#auth-dialog').hidden=false;setConnection('local','請登入共用資料');}}catch(error){setConnection('local','資料載入失敗');const errorBox=$('#auth-error');errorBox.textContent=`雲端已連線，但資料載入失敗：${error.message}`;errorBox.hidden=false;$('#auth-dialog').hidden=false;}}
bootstrap();
