const today = new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium'}).format(new Date());
const seed = {
  locations:[{id:'A-01-01',name:'A架・01層・01格'},{id:'A-02-01',name:'A架・02層・01格'},{id:'B-01-01',name:'B架・01層・01格'}],
  parts:[
    {id:'p1',order:'080410018P',no:'G-UC-312-B006-GI',name:'小球防跳板',book:5},
    {id:'p2',order:'080410018P',no:'UC-122-A001-WE',name:'前控座・白',book:5},
    {id:'p3',order:'080410018P',no:'UC-122-A003-WE',name:'操作面板（LCM・2按）・白',book:5},
    {id:'p4',order:'140909001P',no:'UC-158-F013-WE',name:'前門內貼・白',book:30},
    {id:'p5',order:'140909007P',no:'UC-158-F013-WE',name:'前門內貼・白',book:20}
  ],
  counts:[]
};
const state=JSON.parse(localStorage.getItem('inventory-demo')||'null')||seed;
let currentLocation=null,currentPart=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
let pendingImport=null;
function persist(){localStorage.setItem('inventory-demo',JSON.stringify(state));}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200);}
function totalFor(partId,exceptLocation){return state.counts.filter(c=>c.partId===partId&&c.location!==exceptLocation).reduce((s,c)=>s+c.qty,0);}
function statusFor(p){const actual=totalFor(p.id);if(!state.counts.some(c=>c.partId===p.id))return ['未清點','neutral'];if(actual===p.book)return ['數量一致','good'];if(actual<p.book)return ['數量不足','bad'];return ['數量超出','warn'];}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const labels={count:'現場盤點',dashboard:'盤點總覽',search:'資料查詢',import:'Excel 匯入'};$('#page-title').textContent=labels[name];if(name==='dashboard')renderDashboard();if(name==='search')renderSearch();}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function openLocations(){$('#location-dialog').hidden=false;$('#location-list').innerHTML=state.locations.map(l=>`<button class="location-option" data-id="${esc(l.id)}"><strong>${esc(l.id)}</strong><small>${esc(l.name)}</small></button>`).join('');$$('.location-option').forEach(b=>b.onclick=()=>{currentLocation=state.locations.find(l=>l.id===b.dataset.id);$('#current-location').textContent=`${currentLocation.id}｜${currentLocation.name}`;$('#location-dialog').hidden=true;renderRecent();toast('已鎖定目前儲位');});}
$('#change-location').onclick=openLocations;$('#close-location').onclick=()=>$('#location-dialog').hidden=true;$('#location-dialog').addEventListener('click',e=>{if(e.target.id==='location-dialog')e.currentTarget.hidden=true;});
function searchParts(q){q=q.trim().toLowerCase();return q?state.parts.filter(p=>[p.no,p.order,p.name].some(v=>v.toLowerCase().includes(q))).slice(0,8):[];}
function renderPartResults(q){const found=searchParts(q);$('#search-results').innerHTML=found.map(p=>`<button class="result-item" data-id="${esc(p.id)}"><span><strong>${esc(p.no)}</strong><small>${esc(p.name)}・訂單 ${esc(p.order)}</small></span><span class="result-qty">帳面 ${p.book}</span></button>`).join('')||(q?'<div class="variance warn">查無構件，可到資料查詢確認編號。</div>':'');$$('.result-item').forEach(b=>b.onclick=()=>selectPart(b.dataset.id));}
$('#part-search').addEventListener('input',e=>renderPartResults(e.target.value));
function selectPart(id){if(!currentLocation){openLocations();toast('請先選擇儲位');return;}currentPart=state.parts.find(p=>p.id===id);$('#empty-part').hidden=true;$('#part-form').hidden=false;$('#part-name').textContent=currentPart.name;$('#part-no').textContent=currentPart.no;$('#order-no').textContent=currentPart.order;$('#book-qty').textContent=currentPart.book;$('#other-qty').textContent=totalFor(currentPart.id,currentLocation.id);const s=statusFor(currentPart);$('#part-status').textContent=s[0];$('#part-status').className=`status ${s[1]}`;const existing=state.counts.find(c=>c.partId===id&&c.location===currentLocation.id);$('#actual-qty').value=existing?.qty??'';$('#verified').checked=Boolean(existing?.verified);$('#note').value=existing?.note??'';$('#verify-date').textContent=`確認日：${today}`;$('#search-results').innerHTML='';$('#part-search').value='';updateVariance();$('#actual-qty').focus();}
function updateVariance(){if(!currentPart)return;const raw=$('#actual-qty').value;if(raw===''){ $('#variance-banner').textContent='輸入數量後顯示差異';$('#variance-banner').className='variance neutral';return;}const qty=Number(raw),total=totalFor(currentPart.id,currentLocation.id)+qty,diff=total-currentPart.book;const text=diff===0?'數量一致':diff<0?`數量不足 ${Math.abs(diff)}`:`數量超出 ${diff}`;$('#variance-banner').textContent=`盤點總數 ${total}｜${text}`;$('#variance-banner').className=`variance ${diff===0?'good':diff<0?'bad':'warn'}`;}
$('#actual-qty').addEventListener('input',updateVariance);$('#qty-minus').onclick=()=>{const i=$('#actual-qty');i.value=Math.max(0,Number(i.value||0)-1);updateVariance();};$('#qty-plus').onclick=()=>{const i=$('#actual-qty');i.value=Number(i.value||0)+1;updateVariance();};$('#use-remaining').onclick=()=>{if(!currentPart)return;$('#actual-qty').value=Math.max(0,currentPart.book-totalFor(currentPart.id,currentLocation.id));updateVariance();};
$('#save-count').onclick=()=>{if(!currentLocation||!currentPart)return;const raw=$('#actual-qty').value;if(raw===''||!Number.isInteger(Number(raw))||Number(raw)<0){toast('請輸入有效的整數數量');return;}const qty=Number(raw);let record=state.counts.find(c=>c.partId===currentPart.id&&c.location===currentLocation.id);if(record){record.qty=qty;record.verified=$('#verified').checked;record.note=$('#note').value.trim();record.at=new Date().toISOString();toast('已更新本儲位紀錄');}else{state.counts.unshift({id:crypto.randomUUID(),partId:currentPart.id,location:currentLocation.id,qty,verified:$('#verified').checked,note:$('#note').value.trim(),at:new Date().toISOString()});toast('盤點已儲存');}persist();currentPart=null;$('#part-form').hidden=true;$('#empty-part').hidden=false;renderRecent();$('#part-search').focus();};
function renderRecent(){const rows=state.counts.filter(c=>!currentLocation||c.location===currentLocation.id).slice(0,8);$('#recent-list').innerHTML=rows.map(c=>{const p=state.parts.find(p=>p.id===c.partId);return `<div class="recent-row"><div><strong>${esc(p?.no||'未知構件')}</strong><small>${esc(p?.name||'')}・${esc(c.location)}</small></div><span class="qty">${c.qty} 件</span><small class="when">${new Date(c.at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}</small></div>`}).join('')||'<div class="empty-state"><p>此儲位尚無盤點紀錄</p></div>';}
$('#complete-location').onclick=()=>currentLocation?toast(`${currentLocation.id} 已標記完成`):toast('請先選擇儲位');
function renderDashboard(){const totals=state.parts.map(p=>({...p,actual:totalFor(p.id)}));const completed=totals.filter(p=>p.actual>0).length,match=totals.filter(p=>p.actual===p.book&&p.actual>0).length,short=totals.filter(p=>p.actual<p.book&&p.actual>0).length,over=totals.filter(p=>p.actual>p.book).length;const cards=[['盤點目標',totals.length],['已盤構件',completed],['數量一致',match],['數量異常',short+over]];$('#kpi-grid').innerHTML=cards.map(c=>`<button class="kpi"><span>${esc(c[0])}</span><strong>${c[1]}</strong></button>`).join('');$('#dashboard-table').innerHTML=totals.map(p=>{const d=p.actual-p.book,s=statusFor(p);return `<tr><td>${esc(p.order)}</td><td><strong>${esc(p.no)}</strong></td><td>${p.book}</td><td>${p.actual}</td><td>${d>0?'+':''}${d}</td><td><span class="status ${s[1]}">${s[0]}</span></td></tr>`}).join('');}
function renderSearch(q=''){q=q.toLowerCase();const rows=state.parts.filter(p=>!q||[p.order,p.no,p.name,...state.counts.filter(c=>c.partId===p.id).map(c=>c.location)].some(v=>v.toLowerCase().includes(q)));$('#search-table').innerHTML=rows.map(p=>{const locs=[...new Set(state.counts.filter(c=>c.partId===p.id).map(c=>c.location))];return `<tr><td>${esc(p.order)}</td><td><strong>${esc(p.no)}</strong></td><td>${esc(p.name)}</td><td>${p.book}</td><td>${totalFor(p.id)}</td><td>${esc(locs.join('、')||'—')}</td></tr>`}).join('');}
$('#global-search').addEventListener('input',e=>renderSearch(e.target.value));
$('#camera-button').onclick=()=>toast('相機掃描將在正式連線設定後啟用');
function normalizeHeader(v){return String(v??'').replace(/\s+/g,'').trim();}
function parseWorkbook(wb){const aggregated=new Map();const warnings=[];let sourceRows=0,excluded=0;for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:null,raw:true});const headerIndex=rows.findIndex((r,i)=>i<10&&r.some(v=>normalizeHeader(v)==='物品編號'));if(headerIndex<0){warnings.push(`${sheetName}：找不到「物品編號」標題`);continue;}const headers=rows[headerIndex].map(normalizeHeader);const idx={order:headers.indexOf('採購單編號'),part:headers.indexOf('物品編號'),name:headers.indexOf('品名'),ordered:headers.indexOf('採購數量'),book:headers.indexOf('未交量')};if(idx.order<0||idx.part<0||idx.name<0||idx.book<0){warnings.push(`${sheetName}：必要欄位不完整`);continue;}let order='';for(let r=headerIndex+1;r<rows.length;r++){sourceRows++;const row=rows[r];if(row[idx.order]!=null&&String(row[idx.order]).trim())order=String(row[idx.order]).trim();const part=String(row[idx.part]??'').trim(),name=String(row[idx.name]??'').trim();if(!part||order==='合計'||part.startsWith('備註')){excluded++;continue;}const book=Number(row[idx.book]);if(!order||!Number.isFinite(book)){warnings.push(`${sheetName} 第 ${r+1} 列：訂單或未交量無效`);continue;}const key=`${order}|||${part}`,ordered=idx.ordered>=0&&Number.isFinite(Number(row[idx.ordered]))?Number(row[idx.ordered]):null;if(!aggregated.has(key))aggregated.set(key,{order,no:part,name:name||part,book:0,orderedValues:[],sources:0});const item=aggregated.get(key);item.book+=book;item.sources++;if(ordered!=null)item.orderedValues.push(ordered);if(item.name!==name&&name)warnings.push(`${sheetName} 第 ${r+1} 列：${part} 品名不一致`);}}
  return {items:[...aggregated.values()],warnings,sourceRows,excluded,sheets:wb.SheetNames.length};}
$('#excel-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!window.XLSX){toast('Excel 讀取元件尚未載入');return;}const reader=new FileReader();reader.onload=ev=>{try{const wb=XLSX.read(ev.target.result,{type:'array'});pendingImport=parseWorkbook(wb);const p=pendingImport;$('#import-preview').innerHTML=`<div class="facts" style="margin-top:18px"><div><span>工作表</span><strong>${p.sheets}</strong></div><div><span>可匯入構件</span><strong>${p.items.length}</strong></div><div><span>排除列</span><strong>${p.excluded}</strong></div></div><div class="variance ${p.warnings.length?'warn':'good'}">${p.warnings.length?`有 ${p.warnings.length} 項需要注意；未解析的工作表不會匯入。`:'欄位檢查完成，可以確認匯入。'}</div>`;$('#commit-import').hidden=p.items.length===0;}catch(error){pendingImport=null;$('#commit-import').hidden=true;$('#import-preview').innerHTML='<div class="variance bad" style="margin-top:18px">無法讀取此 Excel，請確認檔案格式。</div>';}};reader.readAsArrayBuffer(file);});
$('#commit-import').onclick=()=>{if(!pendingImport)return;const merged=new Map(state.parts.map(p=>[`${p.order}|||${p.no}`,p]));for(const item of pendingImport.items){const key=`${item.order}|||${item.no}`;if(merged.has(key)){const p=merged.get(key);p.name=item.name;p.book=item.book;}else{const p={id:crypto.randomUUID(),order:item.order,no:item.no,name:item.name,book:item.book};state.parts.push(p);merged.set(key,p);}}persist();toast(`已匯入 ${pendingImport.items.length} 筆帳面資料`);pendingImport=null;$('#commit-import').hidden=true;$('#excel-file').value='';};
$('#export-results').onclick=()=>{if(!window.XLSX){toast('匯出元件尚未載入');return;}const rows=state.parts.map(p=>{const actual=totalFor(p.id),locations=state.counts.filter(c=>c.partId===p.id).map(c=>`${c.location}:${c.qty}`).join('；');return {'訂單編號':p.order,'物品編號':p.no,'品名':p.name,'帳面數量':p.book,'實際數量':actual,'差異':actual-p.book,'儲位分布':locations,'狀態':statusFor(p)[0]};});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'盤點結果');XLSX.writeFile(wb,`盤點結果_${new Date().toISOString().slice(0,10)}.xlsx`);};
function registerWebMcp(){const context=document.modelContext;if(!context?.registerTool)return;context.registerTool({name:'search_inventory_parts',title:'搜尋構件',description:'依訂單、物品編號或品名搜尋目前盤點資料。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:({query})=>searchParts(String(query)).map(p=>({id:p.id,orderNo:p.order,partNo:p.no,name:p.name,bookQty:p.book,actualQty:totalFor(p.id)}))});}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
registerWebMcp();
renderRecent();
